--- #YAML:1.0
name:                Parallel-ForkControl
version:             0.04
abstract:            Finer grained control of processes on a Unix System
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    POSIX:                         0
    Storable:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Brad Lhotsky <brad@divisionbyzero.net>
