# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parallel-ForkControl
version:      0.03
version_from: lib/Parallel/ForkControl.pm
installdirs:  site
requires:
    POSIX:                         0
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
