--- #YAML:1.0
name:               Parallel-ForkControl
version:            0.5
abstract:           Finer grained control of processes on a Unix System
author:
    - Brad Lhotsky <brad@divisionbyzero.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CHI:        0
    POSIX:      0
    Storable:   0
    Try::Tiny:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
